//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitWebLinks.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitWebLinks.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the link..
        /// </summary>
        internal static string GetLinkCommand_Error {
            get {
                return ResourceManager.GetString("GetLinkCommand_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem opening the link..
        /// </summary>
        internal static string GetLinkCommand_FailedToOpenLink {
            get {
                return ResourceManager.GetString("GetLinkCommand_FailedToOpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Git remote &apos;{0}&apos; is not supported. If this is a private Git server, you may need to add the server address to the settings..
        /// </summary>
        internal static string GetLinkCommand_NoHandler {
            get {
                return ResourceManager.GetString("GetLinkCommand_NoHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repository &apos;{0}&apos; does not have a &apos;HEAD&apos; ref for the &apos;{1}&apos; remote. You can fix this by running the command: git remote set-head {1} --auto.
        /// </summary>
        internal static string GetLinkCommand_NoRemoteHead {
            get {
                return ResourceManager.GetString("GetLinkCommand_NoRemoteHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repository &apos;{0}&apos; does not have any remotes..
        /// </summary>
        internal static string GetLinkCommand_NoRemotes {
            get {
                return ResourceManager.GetString("GetLinkCommand_NoRemotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is not tracked by Git..
        /// </summary>
        internal static string GetLinkCommand_NotTrackedByGit {
            get {
                return ResourceManager.GetString("GetLinkCommand_NotTrackedByGit", resourceCulture);
            }
        }
    }
}
