<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GitWebLinks</RootNamespace>
    <AssemblyName>GitWebLinks</AssemblyName>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
    <VsixDeployOnDebug>true</VsixDeployOnDebug>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <UseCodebase>true</UseCodebase>
    <IncludeAssemblyInVSIXContainer>true</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInVSIXContainer>false</IncludeDebugSymbolsInVSIXContainer>
    <IncludeDebugSymbolsInLocalVSIXDeployment>false</IncludeDebugSymbolsInLocalVSIXDeployment>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\..\shared\handlers\*.json">
      <Link>Definitions\%(Filename)%(Extension)</Link>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\icon.png" Link="Resources\icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="..\..\..\LICENSE" Link="Resources\LICENSE" IncludeInVsix="true" />
    <Resource Include="Resources\toast-icon.png" />
    <VSCTCompile Include="VSCommandTable.vsct">
      <Generator>VsctGenerator</Generator>
      <ResourceName>Menus.ctmenu</ResourceName>
      <LastGenOutput>VSCommandTable.cs</LastGenOutput>
    </VSCTCompile>
  </ItemGroup>

  <ItemGroup>
    <None Update="source.extension.vsixmanifest">
      <SubType>Designer</SubType>
      <Generator>VsixManifestGenerator</Generator>
      <LastGenOutput>source.extension.cs</LastGenOutput>
      <IncludeInVSIX>True</IncludeInVSIX>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Web" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Community.VisualStudio.Toolkit.17" />
    <PackageReference Include="Community.VisualStudio.VSCT">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Fluid.Core" />
    <PackageReference Include="Microsoft.VisualStudio.SDK" ExcludeAssets="runtime">
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.SDK.Analyzers">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VSSDK.BuildTools">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
