// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitWebLinks
{
    internal sealed partial class Vsix
    {
        public const string Id = "GitWebLinks.c090a256-229d-440e-8f5d-34306611b61b";
        public const string Name = "Git Web Links";
        public const string Description = @"Copy links to files in their online Git repositories.";
        public const string Language = "en-US";
        public const string Version = "2.14.0";
        public const string Author = "reduckted";
        public const string Tags = "";
    }
}
