// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitWebLinks
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GitWebLinksPackageString = "c79040c1-a271-4bae-b776-be5f65b29c4c";
        public static Guid GitWebLinksPackage = new Guid(GitWebLinksPackageString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int Group_File = 0x1000;
        public const int Group_Selection = 0x1001;
        public const int Group_CopySubMenu = 0x1002;
        public const int Group_OpenSubMenu = 0x1003;
        public const int Menu_SubMenu = 0x2000;
        public const int Command_CopyLinkToFile = 0x0100;
        public const int Command_CopyLinkToSelection = 0x0101;
        public const int Command_CopyLinkToSelectionAtCurrentCommit = 0x0102;
        public const int Command_CopyLinkToSelectionOnCurrentBranch = 0x0103;
        public const int Command_CopyLinkToSelectionOnDefaultBranch = 0x0104;
        public const int Command_CopyLinkToSelectionForTarget = 0x0110;
        public const int Command_OpenLinkToFile = 0x0105;
        public const int Command_OpenLinkToSelection = 0x0106;
        public const int Command_OpenLinkToSelectionAtCurrentCommit = 0x0107;
        public const int Command_OpenLinkToSelectionOnCurrentBranch = 0x0108;
        public const int Command_OpenLinkToSelectionOnDefaultBranch = 0x0109;
    }
}