<Project>

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <RuntimeIdentifiers>win</RuntimeIdentifiers>
        <Nullable>enable</Nullable>
        <LangVersion>13.0</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <AnalysisMode>AllEnabledByDefault</AnalysisMode>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <RootNamespace>GitWebLinks</RootNamespace>
    </PropertyGroup>

</Project>
